name: cyberpunk-distress-ui
static_sites:
- name: web
  source_dir: /
  build_command: npm run build
  output_dir: dist
  index_document: index.html
  error_document: index.html
  catchall_document: index.html
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: GENERATE_SOURCEMAP
    value: "false"