name: cyberpunk-distress-ui
services:
- name: web
  source_dir: /
  github:
    repo: your-username/my-react-app
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /
  health_check:
    http_path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: GENERATE_SOURCEMAP
    value: "false"
  - key: CI
    value: "false"
static_sites:
- name: frontend
  source_dir: /
  github:
    repo: your-username/my-react-app
    branch: main
  build_command: npm run build
  output_dir: dist
  index_document: index.html
  error_document: index.html
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: GENERATE_SOURCEMAP
    value: "false"